project:
  type: website

website:
  title: "STA6349 - Applied Bayesian Analysis - Summer 2025"
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
        
format:
  html:
    theme: minty
    css: styles.css
    toc: false