---
title: "Tentative Schedule"
format: html
---

::: {.callout-tip title="Week 1: 06/17 & 06/19" collapse="true" open="true"}

#### **Tuesday, 06/17/25**

- **Lecture:** 
    - Probability Theory: <a href="files/slides/STA6349-06-17-probability.html">html (view)</a> & <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-06-17-probability.qmd">qmd (code)</a>
    
#### **Thursday, 06/19/25**

- **No class: Juneteenth Holiday**

:::

::: {.callout-tip title="Week 2: 06/24 & 06/26" collapse="true" open="true"}

#### **Tuesday, 06/24**

- **Lecture:** 
    - Bayes' Theorem: <a href="files/slides/STA6349-06-24-bayes-theorem.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-06-24-bayes-theorem.qmd">qmd (code)</a>
    
- **Deliverables:**
    - Assignment 0: Get to Know You (due M 06/30) - see Canvas    

#### **Thursday, 06/28**

- **Lecture:**
    - Random Variables and Their Distributions: <a href="files/slides/STA6349-06-26-random-variables.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-06-26-random-variables.qmd">qmd (code)</a>

:::

::: {.callout-tip title="Week 3: 07/01 & 07/03" collapse="true" open="true"}

#### **Tuesday, 07/01**

- **Deliverables:**
    - Assignment 1: Random Variables (due M 07/07) - <a href="files/assignments/assignment_1.html">html (view)</a> & <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/assignments/assignment_1.qmd">qmd (code)</a>


#### **Thursday, 07/03**

- **No class: Independence Day Holiday**

:::

::: {.callout-tip title="Week 4: 07/08 & 07/10" collapse="true" open="true"}

#### **Tuesday, 07/08**

- **Lecture:**
    - Thinking Like a Bayesian: <a href="files/slides/STA6349-07-08-thinking-bayesian.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-07-08-thinking-bayesian.qmd">qmd (code)</a>

- **Deliverables:**
    - Assignment 2: Thinking Like a Bayesian (due M 07/14) - <a href="files/assignments/assignment_2.html">html (view)</a> & <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/assignments/assignment_2.qmd">qmd (code)</a>

#### **Thursday, 07/10**

- **Lecture:**
    - Conjugate Families: <a href="files/slides/STA6349-07-10-conjugate-families.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-07-10-conjugate-families.qmd">qmd (code)</a>
  

:::

::: {.callout-tip title="Week 5: 07/15 & 07/17" collapse="true" open="true"}

#### **Tuesday, 07/15**


- **Lecture:**
    - Posterior inference and prediction: <a href="files/slides/STA6349-07-15-bayesian-inference.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-07-15-bayesian-inference.qmd">qmd (code)</a>
    
- **Deliverables:**
    - Assignment 3: Conjugate Families & Inference - <a href="files/assignments/assignment_3.html">html (view)</a> & <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/assignments/assignment_3.qmd">qmd (code)</a>

#### **Thursday, 07/17**

- **Deliverables:**
    - Recording of project 1 presentation (due M 07/21)
    - Evaluation of other groups (due F 07/25)

:::

::: {.callout-tip title="Week 6: 07/22 & 07/24" collapse="true" open="true"}

#### **Tuesday, 07/22**

- **Lecture:**
    - Regression in the Bayesian Framework: <a href="files/slides/STA6349-07-22-bayesian-regression.html">html (view)</a> &  <a href="https://github.com/samanthaseals/STA6349Su25/blob/main/files/slides/STA6349-07-22-bayesian-regression.qmd">qmd (code)</a>

#### **Thursday, 07/24**

- **Deliverables:**
    - Assignment 4: Regression Analysis
    
:::

::: {.callout-tip title="Week 7: 07/29 & 07/31" collapse="true" open="true"}

#### **Tuesday, 07/29**

- **Project 2, in class work/planning**
    - You will present in class on Thursday.

#### **Thursday, 07/31**

- **In class presentations!**
    - Group 1
    - Group 2
    - Group 3
    - Group 4
    - Group 5
- **Deliverables:**
    - Evaluation of other presentations (due M 08/04)

:::

::: {.callout-tip title="Week 8: 08/05 & 08/07" collapse="true" open="true"}

#### **Tuesday, 08/05**

- Dr. Seals is out of town at [JSM 2025](https://ww2.amstat.org/meetings/jsm/2025/).
    - You can reach her on Discord and email if needed.
- **Final Exam on Canvas**
    - Each student has 3 hours to complete the exam.
    - Once you open the exam, the timer will continue running.
    - The exam is open note/resources.

#### **Thursday, 08/07**

- Dr. Seals is on her way back from [JSM 2025](https://ww2.amstat.org/meetings/jsm/2025/).
    - You can reach her on Discord and email if needed. (She will be on the road & slow to respond.)
- **Catch up**
    - Please use this class time to catch up with anything you need to catch up with.

:::


