---
title: "Abbreviated Syllabus"
format: html
---

Note: this is an abbreviated syllabus. The full syllabus is available through Classmate and/or Canvas.

### Instructor Information

- [Dr. Samantha Seals](http://samanthaseals.github.io)
-	Office: 4/344

### Meeting Times and Location

-	TR 2:00 pm--4:40 pm
    - 2:00 pm--3:15 pm: Lecture
    - 3:30 pm--4:30 pm: Daily practice
- Physical classroom: 4/406
- Zoom classroom: see Canvas or full syllabus for link

### Office Hours

- Monday: 2:00--4:00 pm (Central)
- Wednesday: 2:00--4:00 pm (Central)
- Other times by appointment

### Grading and Evaluation

The course grade will be determined as follows:

1. Assignments (25%): Every module will finish with an assignment to demonstrate the knowledge gained. These will be like the daily practice, but putting together. The resulting .html file should be submitted to the designated dropbox on Canvas by 11:59 pm on the specified date (see Canvas). 
2. Projects (50%): There are two group projects in this course. The first project will result in a *recorded* presentation while the second project will result in a *live* presentation. Students are required to attend class during live presentations on July 31, 2025.
3. Final Exam (25%): The final exam will be a timed, concepts-based exam. While there may be some calculations needed, you will not be processing raw data. The final exam will be <u>*on Canvas*</u> on August 5, 2025. All students will have 3 hours to complete the exam.

### Late Policy 

Assigments have due dates, however, the dropboxes will not close until the end of the semester. All students are automatically granted "extensions" without question. 
Note that if there is not a submission when I go to grade (after the initial deadline), I will assign a zero (0) and request that you submit the assignment when you are able to. This is only for record keeping purposes. There is no penalty for submitting late and a full grade will be given upon review of your submission.

**Extensions are *not available* for projects or the final exam.**
